[limitation]
ip_limitation=20 #Лимит открытых соединений с 1 ip, -1 отключает лимит -- Необязательный(20)
client_timeout="5s" #timeout для клиента, -1 отключает, Поддерживает разные временные еденицы и их слияние -- Необязательный("5s")
