mode="reverse_proxy" #scety будет работать в нескольких режимах, пока с реверсивным прокси работаем
listen_port = 80 #XOR(или то или то, иначе ошибка) listens_port = [80, 443] -- Обязательный параметр
host = "*.example.com" #XOR hosts = ["localhost", "*"] -- Необязательный параметр("*")

[upstream]
port=3000 #XOR ports=[3232, 4545](включит распределенние между портами) -- Обязательный
ip_limitation=20 #Лимит открытых соединений с 1 ip, -1 отключает лимит -- Необязательный(20)
client_timeout="5s" #timeout для клиента, -1 отключает, Поддерживает разные временные еденицы и их слияние -- Необязательный("5s")
service_timeout="30s" #timeout для сервиса, также как и с таймаутом клиента

#если вместо listen_port стоит listens_port, то требуем:
#[upstream_{port}]
#для каждого порта из listens_port
#если есть например [upstream_6767], но у нас listens_port=[80, 443], то выдаем ошибку типо "... port 6767 found, maybe there was listens_port=[80, 443, 6767]?"


[sll]
cert="/etc/ssl/cert"
key="/etc/ssl/key"

#Почти как и с upstream, требуем указать для какого именно порта сертификат, иначе ошибка. Но не для каждого порта требуем сертификат

[headers]
# заголовки которые добавляем к запросу идущему на апстрим
[headers.upstream]
X-Custom-Header = "value"
X-Another = "something"

# заголовки которые добавляем к ответу клиенту
[headers.response]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"